import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:mealmate/firebase_options.dart';
import 'package:mealmate/pages/init_pages/splashscreen.dart';
import 'package:mealmate/theme/themedata.dart';
import 'package:provider/provider.dart';

import 'AdminPanel/collectionUploadModelProvider/collectionProvider.dart';
import 'models&ReadCollectionModel/cartmodel.dart';
import 'models&ReadCollectionModel/userReadwithCollection.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    /// This is the default options for Firebase TO CHOSE THE PLATFORM TO INITTIALIZE , THUS WHETHER WEB / ANDROID / IOS
    /// You can change the options in the file firebase_options.dart WHICH IS IN THE ROOT DIRECTORY THAT GENERATED BY THE CLI
    /// WHEN YOU RUN THE COMMAND `flutterfire configure`
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => CartModel()),
        ChangeNotifierProvider(create: (context) => AdminCollectionProvider()),
        ChangeNotifierProvider(create: (context) => userCollectionProvider())
      ],
      child: MaterialApp(
          debugShowCheckedModeBanner: false,
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          home: Scaffold(
            body: SplashScreen(),
          )),
    );
  }
}

// I USED THE CLASS BELLOW TO VERIFFY IF FIREBASE IS WORKING
class MyHomePage extends StatelessWidget {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  MyHomePage({super.key});

  Future<void> _addTestDocument() async {
    await _firestore.collection('test').add({'field': 'value'});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.green,
      appBar: AppBar(
        title: Text('Firebase Check'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Center(
          child: ElevatedButton(
            onPressed: _addTestDocument,
            child: Text('Add Test Document'),
          ),
        ),
      ),
    );
  }
}
